[package]
name = "oblivion_ui"
version = "1.0.0"
edition = "2021"

[dependencies]
sdl2 = "0.36"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }

[[bin]]
name = "oblivion-cli"
path = "src/bin/oblivion-cli.rs"